try{
 console.log('something');   
}
catch(err){
    console.log('something else');
}